### ISSUE TITLE
error password for klaneds

### ISSUE THREAD

**Issue by Xiangzhaohong** [kaist-avelab/K-Lane#1]
hi thanks for the dataset
but maybe this password is wrong and i cannot login?

**Comment by DongHeePaek** [comment]
Hello, @Xiangzhaohong

Thank you for your interest in our dataset. I confirmed that the dataset is being accessed. Could you check if you distinguished the case of the password? Actually, there is an uppper case letter 'K' in the password.

Thank you.

**Comment by Xiangzhaohong** [comment]
@dhepaek hi, thanks, it's my wrong.
the password is ok!
