### ISSUE TITLE
Where is rosbag demo for your annotation tool?

### ISSUE THREAD

**Issue by earlysleepearlyup** [kaist-avelab/K-Lane#11]
Thanks for your excellent work！But could you please provide a rosbag demo file if it is convenient?
And do we need to provide a rosbag in the same format as yours If using your tool？

**Comment by DongHeePaek** [comment]
Hello, @earlysleepearlyup

I appreciate your interest in our work.

Actually, we do not provide example rosbag files, but if you need the file, we will provide it.

Thank you.

**Comment by vehxianfish** [comment]
> Hello, @earlysleepearlyup
> 
> I appreciate your interest in our work.
> 
> Actually, we do not provide example rosbag files, but if you need the file, we will provide it.
> 
> Thank you.

Thanks for your wonderful work~. I was wondering if you could provide the BAG and release the code for BAG online reasoning
