### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by fengjiang5** [kaist-avelab/K-Lane#3]
Hello, thanks for your great job on lane detection based on point cloud. And I want to download this data for server. But maybe it can only achieve by downloading on windows. So is there any ways for me to download the data directly with Linux command line on server.

Hope for your reply.

**Comment by DongHeePaek** [comment]
Hello, @fengjiang5.

Since we are using the synology disk station, we feel sorry about not providing a command line.
We confirm the dataset downloading and working fine on Linux systems with GUI, such as Ubuntu 18.04.

Thank you.
