### ISSUE TITLE
Validation dataloader error in training: error each element in list of batch should be of equal size 

### ISSUE THREAD

**Issue by MIXIAOXIN** [kaist-avelab/K-Lane#5]
Hi, thanks for your fantastic work.
In training, I encountered a data loader error for validation after 1 epoch. 
The error message is:
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size
batch: 3it [00:36, 12.01s/it]
val:   2%|▎         | 1/40 [00:11<07:21, 11.33s/it]
epoch=0/35, loss=16.124535306149284 

I wonder if the cause of the error is the test data format or something else? Thanks in advance.

**Comment by DongHeePaek** [comment]
Hello, @MIXIAOXIN.
Thank you for your interest in our research.

Please uncomment the changed code (line 32 to 51) on K-Lane/baseline/datasets/registry.py.
We confirmed that changing the batch_size of validation to 1 fixes this error when it happens.
However, this is only a temporary solution.
We will find and correct the main cause of the error.

Thank you for the report.

**Comment by ywfwyht** [comment]
> Hi, thanks for your fantastic work. In training, I encountered a data loader error for validation after 1 epoch. The error message is: raise RuntimeError('each element in list of batch should be of equal size') RuntimeError: each element in list of batch should be of equal size batch: 3it [00:36, 12.01s/it] val: 2%|▎ | 1/40 [00:11<07:21, 11.33s/it] epoch=0/35, loss=16.124535306149284
> 
> I wonder if the cause of the error is the test data format or something else? Thanks in advance.
me too

**Comment by MIXIAOXIN** [comment]
> Hello, @MIXIAOXIN. Thank you for your interest in our research.
> 
> Please uncomment the changed code (line 32 to 51) on K-Lane/baseline/datasets/registry.py. We confirmed that changing the batch_size of validation to 1 fixes this error when it happens. However, this is only a temporary solution. We will find and correct the main cause of the error.
> 
> Thank you for the report.


Thanks for your reply.
Actually, I modified the code in K-Lane/baseline/datasets/klane.py, line 123
#temp_data_info['description'] = desc      # original code
temp_data_info['description'] = desc[-3:]  # modified by Xiaoxin
It also works now. I wonder if the change is correct?

**Comment by DongHeePaek** [comment]
Hello, @MIXIAOXIN 

We modified the code in K-Lane/baseline/datasets/klane.py (line 123-126) and K-Lane/baseline/engine/runner.py (line 132, 472).
Since the description information is required in the conditional evaluation, we made the flag to deal with the problem.

Thank you.
