### ISSUE TITLE
Multiple GPUS training errors

### ISSUE THREAD

**Issue by ywfwyht** [kaist-avelab/K-Lane#6]
Hi, brother！ 

RuntimeError: Caught RuntimeError in replica 1 on device 1.
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by DongHeePaek** [comment]
Hello, @ywfwyht.

Thank you for your interest in our research.
Since we did not need the training in multiple-GPUs, we have not implemented it.
If you need the multiple-GPU training, we will modify the pipeline.

Thank you.

**Comment by ywfwyht** [comment]
@dhepaek ，Thanks a lot, I need the multiple-GPUs.
