### ISSUE TITLE
Dataset download very slow

### ISSUE THREAD

**Issue by nicoduchene** [kaist-avelab/K-Lane#8]
Hello!

First, thank you for the nice work in the 3D lane annotation space, it's a welcome sight!
I've been trying to download the dataset, but the download time is particularly slow, and there are network issues that force me to start the download over again. 

Have you considered hosting this data elsewhere? For example google drive?

Thanks,
Nicolas

**Comment by DongHeePaek** [comment]
Hello, @nicoduchene.

The server's network issue is resolved.
In addition, we make our dataset accessible via Google Drive, for which we update the URLs on the GitHub main page.

Thank you,
Donghee
