### ISSUE TITLE
What is the use of data['meta'] in the network

### ISSUE THREAD

**Issue by ywfwyht** [kaist-avelab/K-Lane#9]
Hi, guys.

           The data structure will affect my ability to export the ONNX model,  and how to convert the torch model to ONNX model

**Comment by DongHeePaek** [comment]
Hello, @ywfwyht 

The data corresponding to'meta' are typically for file paths (for example, pcd or txt files).

Thank you.

**Comment by ywfwyht** [comment]
hi @dhepaek 
Therefore, it is not actually used in network forward propagation？

**Comment by DongHeePaek** [comment]
@ywfwyht Yes.
